export const group42Data = {
    className: "group-3",
};

export const siteOnePagerData = {
    service: "Service",
    useCases: "Use Cases",
    developers: "Developers",
    pricing: "Pricing",
    resources: "Resources",
    company: "Company",
    forBusinessUsers: "For business users",
    forDevelopers: "For developers",
    rectangle: "/img/rectangle@1x.png",
    text1: "Seriously beautiful code deploy <br />with IP, DNS, SSL control",
    x16334393115111: "/img/1633439311511-1@1x.png",
    resilient: "RESILIENT",
    text15: "Build Resilient deployments",
    simple: "Simple",
    dnsAndSslSimple: "DNS and SSL simple",
    title: "+ more power",
    control: "CONTROL",
    text16: "Protect growth from Vendor Lock",
    moveFaster: "move faster",
    text17: "WHAT WILL YOU BUILD?",
    text18: "Start Building for Free",
    viewCaseStudy: "View case study",
    webhooks: "Webhooks",
    text21: "Some applications need to listen to web hooks to receive important events<br />Expose your app on your laptop and use simple URLs",
    learnMore: "Learn more",
    text22: "Expose API port + web",
    text23: "Most web and mobile apps provide multiple port such as one for the web and one for APIS. We provide per port DNS entries",
    learnMore2: "Learn more",
    secureApps: "Secure<br />Apps",
    text24: "Sometimes it’s not enough to secure the apps but necessary to secure the network itself. Virtual DMZ to the rescue",
    learnMore3: "Learn more",
    routing: "Routing",
    text25: "Routing in production can be hard, changing origin for APIs “in-flight” ca be daunting. Virtual DMZ to the rescue",
    learnMore4: "Learn more",
    text27: "Buil-in redundancy management",
    distributedDns: "Distributed DNS",
    text28: "< 50ms global propagation",
    monitoring: "Monitoring",
    text29: "IPs instantly retoutable through BGP",
    text30: "Server side rendering support",
    text31: "GET STARTED WITH SETIP.IO",
    hostedOnSetipIo: "Hosted on setip.io",
    text2: "From prototype to hyper growth",
    text9: ".",
    text3: "Live DNS/PORT redirect for non-stop operations",
    text4: "Own your IP<br />No vendor lock",
    text8: "Provide whole-team autonomy with a platform that is developer approved",
    getStartedFree: "Get Started Free",
    text10: "Scale without interruption from prototype to hyper growth",
    aloYoga: "ALO YOGA",
    text11: "Scale without interruption from prototype to hyper growth",
    simpleApi: "Simple API",
    text12: "The most powerful and flexible drag and drop visual editor",
    distributedDns2: "Distributed DNS",
    text13: "A/B test experiences, target content, and segment audiences to drive growth",
    text14: '"Curl registration is genius for developers " Jeremy B. Developer and Entrepreneur, founder of Adalo, the amazing No Code platform.',
    spanText: `Stripe raising additional couple billion dollars, Patrick admits he's "scared to IPO. but believes Setip.IO is the way to go” <br />`,
    spanText2: "<br />Softbank-injected dropbox alternative. Google Employee DeFi hacking. Out of touch, ad buying venture investor. Snapchat-based GPT-3 written poetry. Oculus-based creator economy Miami-moving capitalist.",
    patricKingCto: "PATRIC KING, CTO",
    everlane: "EVERLANE",
    text20: "Business autonomy. Developer approved.",
    text26: "We are reliability obsessed",
    text32: "One Curl call away...",
    text33: "Or try our “out of this world” UI",
    getStartedFree2: "Get Started Free",
    talkToSales: "Talk to sales",
    text34: "Connect any device, from anywhere, test, stage and deploy anywhere",
    getStarted: "Get Started",
    logIn: "Log in",
    developers2: "DEVELOPERS",
    text35: "Setip.io for Developers",
    developerDocs: "Developer Docs",
    text36: "Open Source Projects",
    integrations: "INTEGRATIONS",
    curl: "Curl",
    nodejs: "Nodejs",
    python: "Python",
    nextJs: "Next.js",
    gatsby: "Gatsby",
    place: "Rust",
    nodejs2: "Nodejs",
    python2: "Python",
    nextJs2: "Next.js",
    gatsby2: "Gatsby",
    resources2: "RESOURCES",
    userGuides: "User Guides",
    blog: "Blog",
    communityForum: "Community Forum",
    saasTemplates: "SaaS Templates",
    partners: "Partners",
    offering: "OFFERING",
    features: "Features",
    pricing2: "Pricing",
    useCases2: "USE CASES",
    text37: "Web hooks development",
    virtualDmz: "Virtual DMZ",
    text38: "Expose API port + web",
    secureApps2: "Secure Apps",
    routing2: "Routing",
    company2: "COMPANY",
    about: "About",
    careers: "Careers",
    text39: "🚀",
    copyright: "© 2021 Setipio, LLC",
    security: "Security",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    group4Props: group42Data,
};

export const webSiteOnePagerData = {
    siteOnePagerProps: siteOnePagerData,
};

